@startuml
skinparam classAttributeIconSize 0

interface Card {
  +name: CardName
  +value: number
  +color: CardColor
  +owner: string
}

enum CardColor {
  HEARTS
  DIAMONDS
  CLUBS
  SPADES
}

enum CardName {
  two
  three
  four
  five
  six
  seven
  eight
  nine
  ten
  jack
  queen
  king
  ace
}

class Game {
  #players: Player[]
  +Game()
}

class CardGame {
  +CardGame()
  #setDealerChip()
  #updateDealerChip()
  #resetBets()
  #setDeafaultBets()
  #bet()
}

class Poker {
  -pokerDeck: PokerDeck
  -pokerDeskCards: Card[]
  +Poker()
  -startGame()
  -nextRound()
  -handCardsOut()
  -resetCards()
  -playRound()
}

class Blackjack {
}

class Player {
  -playerId: string
  -username: string
  -displayname: string
  -balance: number
  -cards: Card[]
  -hasDealerChip: boolean
  -bet: number
  +Player(playerId: string, username: string, \n  displayname: string, balance: number, \n  hasDealerChip: boolean, bet: number)
  +getPlayerId(): string
  +getUsername(): string
  +getDisplayname(): string
  +getDealerChip(): boolean
  +setDealerChip(hasDealerChip: boolean): void
  +getBet(): number
  +setBet(bet: number): void
  +addCard(card: Card, playerId: string): void
  +clearHand(): void
  {static} +xNextPlayer(players: Player[], i: number, x: number): number
  {static} +nextPlayer(players: Player[], i: number): number
  {static} +playerWithDealerChip(players: Player[]): number
}

class CardGamePlayer {
}

class PockerPlayer {
}

class Deck {
  #deck: Card[]
  +Deck()
  #shuffle(cardDeck: Card[]): void
  +dealCard(cardDeck: Card[], id: string): Card
  +getDeck(): Card[]
}

class BlackjackDeck {
  +BlackjackDeck()
  -blackjackDeckInit(): void
}

class PokerDeck {
  +PokerDeck()
  -pokerDeckInit(): void
}

' Inheritance
Game <|-- CardGame
CardGame <|-- Poker
CardGame <|-- Blackjack
Deck <|-- BlackjackDeck
Deck <|-- PokerDeck
Player <|-- CardGamePlayer
CardGamePlayer <|-- PockerPlayer

' Associations
Game o-- "many" Player : contains
Poker *-- "many" Card : pokerDeskCards
Player *-- "many" Card : cards
Deck *-- "many" Card : deck
Poker o-- "1" PokerDeck : uses

@enduml