@startuml

left to right direction

rectangle "UCD Online Casino" {
    
    rectangle "Hauptmenü" {
      (Poker spielen)
      (Blackjack spielen)
      (Slot Machine spielen)
      (Roulette spielen)
    }
    
    rectangle "Social Features" {
      (Freundschaftsanfrage senden)
      (Freunde verwalten)
      (Chatnachricht senden)
    }
    
    Spieler --> (Poker spielen)
    Spieler --> (Blackjack spielen)
    Spieler --> (Slot Machine spielen)
    Spieler --> (Roulette spielen)
    
    Spieler --> (Freundschaftsanfrage senden)
    Spieler --> (Freunde verwalten)
    Spieler --> (Chatnachricht senden)
    Gast --> (Einloggen)
}


@enduml